northwind:
  target: dev
  outputs:
    dev:
      type: redshift
      host: redshift-cluster-learn.cvvgdabzn6nk.us-east-1.redshift.amazonaws.com
      user: awsuser
      password: 12345678aA
      port: 5439
      dbname: northwind
      schema: dbt_ana
      threads: 4